// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANWoPSVY0zMG9QavDI98JBmdg4rLB70iM',
    appId: '1:729508684037:web:851398e776a11074d6176c',
    messagingSenderId: '729508684037',
    projectId: 'hat-shop3',
    authDomain: 'hat-shop3.firebaseapp.com',
    storageBucket: 'hat-shop3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi_iuO7p2N8FuVXVQ8vT0OmSsfM2wPnuU',
    appId: '1:729508684037:android:a0eaa87932368b49d6176c',
    messagingSenderId: '729508684037',
    projectId: 'hat-shop3',
    storageBucket: 'hat-shop3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsIrCJit_cXmbxabAIiyny-kfCFNZwa3I',
    appId: '1:729508684037:ios:ada7285f198d64c0d6176c',
    messagingSenderId: '729508684037',
    projectId: 'hat-shop3',
    storageBucket: 'hat-shop3.appspot.com',
    iosClientId: '729508684037-ljdsbdf5mt5tv6ijv9n3e2dnfqkr9hr1.apps.googleusercontent.com',
    iosBundleId: 'com.example.hatShop',
  );
}
